site_name: tesswcs
nav:
    - Home: README.md
    - Tutorial: tutorial.md
theme:
  name: "material"
  icon:
      logo: material/globe-model
  palette:
    scheme: default
    primary: red
    accent: blue
repo_url: https://github.com/christinahedges/tesswcs
plugins:
  - search
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences